language: python

python:
    - 3.3
    - 3.4

env:
    - PYTHONASYNCIODEBUG=1
    - PYTHONASYNCIODEBUG=0

before_install:
    - sudo add-apt-repository -y ppa:chris-lea/redis-server
    - echo "deb http://ppa.launchpad.net/chris-lea/redis-server/ubuntu oneiric main" | sudo tee -a /etc/apt/sources.list
    - sudo apt-get update -qq
    - sudo apt-get install redis-server

install:
    - pip install aioredis
    - pip install mmh3
    - pip install flake8
    - pip install nose
    - pip install -e .
    - pip install coveralls

before_script:
    - redis-server --daemonize yes --pidfile ./redis-server.pid
    - sleep 3

script:
    - make cov

after_success:
    - coveralls
